### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by lastgodking** [zeffii/bpy_externall#6]
I have tried many methods in the past two days, but there is no way to solve this problem. The new statement will cause more errors, and other encodings have been tried, but the problem remains.
The following is the error description.

 Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\bpy_externall-master\__init__.py", line 138, in modal
    self.process()
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\bpy_externall-master\__init__.py", line 123, in process
    fp = filepath_read_handler()
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\bpy_externall-master\__init__.py", line 82, in filepath_read_handler
    fp = f.read()
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 9: invalid continuation byte

**Comment by lastgodking** [comment]
I hope the author can see and help solve it, thank you!!
